openapi: 3.0.3

info:
  title: OpenAPI Gym
  description: info.description here.
  contact:
    name: hainet50b
    url: https://github.com/hainet50b
    email: 20400616+hainet50b@users.noreply.github.com
  license:
    name: Pmacho Licence
    url: https://github.com/hainet50b
  version: 1.0.0

servers:
  - url: https://{service}.programacho.com
    description: programacho.com (prod)
    variables:
      service:
        enum:
          - pages
          - blog
        default: pages
        description: サブドメインを選択してください。
  - url: https://{service}.dev.programacho.com
    description: programacho.com (dev)
    variables:
      service:
        default: pages
        description: サブドメインを入力してください。

paths:
  /v1/users:
    get:
      summary: ユーザー取得
      description: ユーザーを取得します。
      externalDocs:
        url: https://github.com/hainet50b
      operationId: getUsers
      security:
        - basic: []

security:
  - basic: []

components:
  securitySchemes:
    basic:
      type: http
      scheme: basic
