openapi: 3.0.3

info:
  title: OpenAPI Gym
  description: info.description here.
  contact:
    name: hainet50b
    url: https://github.com/hainet50b
    email: 20400616+hainet50b@users.noreply.github.com
  license:
    name: Pmacho Licence
    url: https://github.com/hainet50b
  version: 1.0.0

servers:
  - url: https://{service}.programacho.com
    description: programacho.com (prod)
    variables:
      service:
        enum:
          - pages
          - blog
        default: pages
        description: サブドメインを選択してください。
  - url: https://{service}.dev.programacho.com
    description: programacho.com (dev)
    variables:
      service:
        default: pages
        description: サブドメインを入力してください。

paths:
  /v1/users:
    get:
      summary: ユーザー取得
      description: ユーザーを取得します。
      externalDocs:
        url: https://github.com/hainet50b
      operationId: getUsers
      security:
        - basic: []
      responses:
        "200":
          $ref: "#/components/responses/findUsers"

security:
  - basic: []

components:
  parameters:
    ContentType:
      name: Content-Type
      in: header
      description: Content-Type
      required: true
      allowEmptyValue: false
      example: "application/json; charset=UTF-8"
  responses:
    findUsers:
      description: 正常
      headers:
        "Content-Type":
          $ref: "#/components/parameters/ContentType"
      content:
        "application/json":
          schema:
            $ref: "#/components/schemas/User"
  schemas:
    User:
      type: object
      properties:
        id:
          description: ユーザーID
          type: string
          maxLength: 36
          example: n77b65b76-32f0-4398-97f0-a2c74e29ffed
        name:
          description: ユーザー名
          type: string
          maxLength: 32
          example: hainet50b
      required:
        - id
        - name
  securitySchemes:
    basic:
      type: http
      scheme: basic
